### ISSUE TITLE
:bug: QProcessing demo doesn't work with selected features

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin-processing#13]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

You can test ite here

https://v37.g3wsuite.it/it/map/qprocessing/qdjango/263/

This is the errore message: 'NoneType' object has no attribute 'fields'

### Steps to reproduce

Select some points of layer 'Reference points for analysis'

Open the processing toolbar

Select the option 'Only selected features'

Run the processs

### Environment

- g3w-admin: __v3.7.4__
- g3w-client: __3.9.3__
- browser: __Chrome 120.0.0.0__
- operating system: __Linux 64-bit__

### Link to your project

https://v37.g3wsuite.it/it/map/qprocessing/qdjango/263/

**Comment by wlorenzetti** [comment]
@leolami check now, the projects should be work.

**Comment by leolami** [comment]
Perfect, it works well

I only noticed that now you can choose CSV as output, but if I launch the process in the results the SCV does not appear as downloadable

**Comment by wlorenzetti** [comment]
We must wait @volterra79 per csv output.
