### ISSUE TITLE
Create a direct link to projects in projects-models list.

### ISSUE THREAD

**Issue by wlorenzetti** [g3w-suite/g3w-admin-processing#6]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin-processing/issues) to make sure this feature hasn't been requested already.

### Motivation

It could be useful add shortcuts to every projects name and make possible make download of the model if the user has permissions.

### Suggested solution

Add shortcuts for _projects show_ map and for _project editing page_ (if user has permission) near every projects name into the list. 
Render the processing model file path a link for the download.

![Screenshot_20230828_092705](https://github.com/g3w-suite/g3w-admin-processing/assets/196809/69a67491-2271-4e03-8cc6-ab02f9df3111)

**Comment by Raruto** [comment]
Closed by: https://github.com/g3w-suite/g3w-admin-processing/pull/7
